canonifyurls = false
paginate = 100

# Set to true to enable syntax highlighting in code fences with a language tag
pygmentsCodefences =  true

# color-codes for highlighting derived from this style
pygmentsStyle = "manni"


[params]
  DateForm = "January 2, 2006"
  Description = "Your Blog Description"
  DescriptionMeta = "Your Blog Description"
  Author = "Your Name"
  postSummariesFrontPage = 5
  showReadTime = false
  defaultHeaderImage = "/images/bg.png"
  mainSections = ["posts"]
  copyright = "Created with ♥ by <a href='/about/'>Your Name</a>. All content is the property of <Your Name> and <Site Url>. This blog, its content, and opinions are my own."

# Allow HTML to be included from Markdown files
[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[params.sidebar]
  # How many posts to show on the sidebar (Default: 5)
  num_recent_posts = 5
  recent_articles = true
  categories = true
  archive = true
  feed = true

[taxonomies]
  series = "series"
  tag = "tags"
  category = "categories"

[permalinks]
  blog = "/:filename/"
  page = "/:slug/"
  posts = "/:filename/"
